version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Keep the scanner engine stable by ignoring these major updates
      - dependency-name: "lighthouse"
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "lighthouse"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
